=== Dinesh1631/SpringLearning/JPA/bin/persistance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="persistence">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="persistence-unit">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="class" type="xs:string" />
							<xs:element name="properties">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" use="required" />
												<xs:attribute name="value" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Dinesh1631/SpringLearning/JPA/bin/persistance.xml
<persistence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="persistance.xsd">  
<persistence-unit name="Student_details">  
      
    <class>com.javatpoint.jpa.student.Student</class>  
  
<properties>  
<property name="javax.persistence.jdbc.driver" value="com.mysql.jdbc.Driver"/>  
<property name="javax.persistence.jdbc.url" value="jdbc:mysql://localhost:3306/studentdata"/>  
<property name="javax.persistence.jdbc.user" value="root"/>  
<property name="javax.persistence.jdbc.password" value=""/>  
<property name="eclipselink.logging.level" value="SEVERE"/>  
<property name="eclipselink.ddl-generation" value="create-or-extend-tables"/>  
</properties>  
  
    </persistence-unit>  
</persistence>
